### ISSUE TITLE
503 returned for requests to exact paths matched with "begins_with"

### ISSUE THREAD

**Issue by svtfrida** [SVT/orm#37]
One of our users reports nonintuitive behavious when using `begins_with` path matching.

The example rule looks like this (user-specific information removed):

```
...
  - description: Redirect traffic to subpath
    domains:
      - host.domain.example
    matches:
      all:
        - paths:
            begins_with:
              - "/mypath"
    actions:
...
```

Expected behaviour:
Requests to `https://host.domain.example/mypath` should be handled by the rule and sent to the configured backend.

Actual behaviour:
Requests to `https://host.domain.example/mypath` return error code 503: `VCL failed`, while requests to `https://host.domain.example/mypath/` (with trailing slash) are handled correctly.

Needs reproducing and further investigation.

**Comment by svtfrida** [comment]
Workaround: Use a separate exact match to handle the case explicitly.

```
...
  - description: Redirect traffic to subpath
    domains:
      - host.domain.example
    matches:
      any:
        - paths:
            exact:
              - "/mypath"
        - paths:
            begins_with:
              - "/mypath/"
    actions:
...
```

**Comment by splushii** [comment]
The root cause for the behaviour in this specific case is a rule on the form:
```yaml
  - description: A VCL_Error generating rule
    domains:
      - example.com
    matches:
      all:
        - paths:
            begins_with:
              - "/path"
    actions:
      backend:
        origin: https://some.domain.example.com
      req_path:
        - prefix:
            remove: '/path'
```
which makes the variable `path` in Varnish to `""` and later there will be a `set req.url = variable.get("path");` which is not allowed because it triggers
```
--  VCL_Error      Setting req.url to empty string
```

So to fix this there needs to be some check for the empty string in the `path` variable. Something like
```c
if (variable.get("path") != "") {
  set req.url = variable.get("path");
} else {
  set req.url = "/"
}
```

**Comment by svtfrida** [comment]
**Workaround**

Use regex replace to set the request path without turning it into an empty string:

```
    actions:
      req_path:
        - replace:
            from_regex: /mypath/?(.*)
            to_regsub: /\1
```
