### ISSUE TITLE
Support additional loadbalancer algorithms

### ISSUE THREAD

**Issue by nsg** [SVT/orm#5]
For example, something like this:

```yaml
backend:
  servers:
    - server: server1
      weight: 30
    - server: server2
      weight: 70
  balance: roundrobin
```
